version: 2.1

jobs:
  ast-scan:
    docker:
      - image: checkmarx/ast-cli
    steps:
    - checkout
    - run:
        name: Execute CxAST scan
        command: |
          /app/bin/cx scan create --agent "${AST_AGENT}" --base-uri "${AST_BASE_URI}" --client-id "${AST_CLIENT_ID}" --client-secret "${AST_CLIENT_SECRET}" --tenant "${AST_TENANT}" --project-name "${CIRCLE_PROJECT_REPONAME}" --branch "${CIRCLE_BRANCH}" --scan-types "${AST_SCANTYPE}" --sast-preset-name "${SAST_SCAN_PRESET}" --output-path "./reports" --report-format "${REPORT_FORMAT}" --file-source . ${PARAMS}
    - store_artifacts:
        path: "./reports"

workflows:
  ast-workflow:
    jobs:
      - ast-scan